### PR TITLE
feat(node-app): Show account level sync status

### PR DESCRIPTION
**Pull request by rohanjadvani**
## Description

Render a warning per account card depending on the account's head and remove the global wallet sync status.

## Testing

image

### CODE REVIEW

**Comment by jowparks** [comment]
On the account page itself there is still a warning even if the account head is up to date:
Screenshot 2023-06-06 at 4 06 03 PM

We should probably update that too.

Otherwise looks great!

**Review by jowparks — APPROVED** [review]

**Comment by skylarrichard123** [comment]
Can we update the preview link above, doesn't seem to be showing this new work.

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
(1) Let's remove the global account sync warning above the accounts since it's redundant 
(2) Let's change the account level warning to "Account Syncing: 85.68% | Balance may be inaccurate during sync"

**Comment by rohanjadvani** [comment]
@skylarrichard123 Updated

image

**Review by skylarrichard123 — APPROVED** [review]

**Pull request merged**
